[package]
name = "stdx"
version = "0.1.0"
edition = "2021"
license = "0BSD OR Unlicense OR CC0-1.0"
publish = false

[features]

[dependencies]
stdx_core = { path = "./core" }
stdx_soa = { path = "./soa" }
